/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EnvSensorWorkArea;

import Business.Oragnization.Organization;
import Business.Oragnization.Organization.EnvironmentSensorManagementType;
import Business.Oragnization.OrganizationDirectory;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apurv
 */
public class EnvironmentSensorOrganizationJPanel extends javax.swing.JPanel {

    private OrganizationDirectory directory;
    private JPanel userProcessContainer;
    /**
     * Creates new form EnvironmentSensorOrganizationJPanel
     */
    public EnvironmentSensorOrganizationJPanel(JPanel userProcessContainer, OrganizationDirectory directory) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.directory = directory;
        
        populateTable();
        populateCombo();
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_org.getModel();

        model.setRowCount(0);

        for (Organization organization : directory.getOrganizationList()) {
            Object[] row = new Object[1];

            row[0] = organization;

            model.addRow(row);
        }
    }
    
    private void populateCombo() {
        combo_Organization.removeAllItems();
        for (Organization.EnvironmentSensorManagementType type : Organization.EnvironmentSensorManagementType.values()) {
            if (!type.getValue().equals(Organization.EnvironmentSensorManagementType.EnvironmentSensorAdmin.getValue())) {
                combo_Organization.addItem(type);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        combo_Organization = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_org = new javax.swing.JTable();
        btn_back = new javax.swing.JButton();
        btn_add_org = new javax.swing.JButton();
        btn_delete_Org = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 102));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Organization Type ");
        add(jLabel1);
        jLabel1.setBounds(53, 305, 190, 30);

        combo_Organization.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_Organization.setForeground(new java.awt.Color(0, 0, 51));
        combo_Organization.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_Organization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_OrganizationActionPerformed(evt);
            }
        });
        add(combo_Organization);
        combo_Organization.setBounds(298, 306, 268, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Environment Sensor Organization");
        add(jLabel2);
        jLabel2.setBounds(200, 40, 450, 29);

        tbl_org.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ));
        jScrollPane2.setViewportView(tbl_org);

        add(jScrollPane2);
        jScrollPane2.setBounds(81, 101, 452, 112);

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back_Final.png"))); // NOI18N
        btn_back.setText("<<Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        add(btn_back);
        btn_back.setBounds(10, 10, 95, 40);

        btn_add_org.setBackground(new java.awt.Color(0, 0, 255));
        btn_add_org.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_org.setText("Add Organization");
        btn_add_org.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_orgActionPerformed(evt);
            }
        });
        add(btn_add_org);
        btn_add_org.setBounds(82, 445, 140, 50);

        btn_delete_Org.setBackground(new java.awt.Color(0, 102, 255));
        btn_delete_Org.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete_Org.setText("Delete Organization");
        btn_delete_Org.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_OrgActionPerformed(evt);
            }
        });
        add(btn_delete_Org);
        btn_delete_Org.setBounds(380, 440, 170, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sensor.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(570, -40, 960, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void combo_OrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_OrganizationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_OrganizationActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_add_orgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_orgActionPerformed
        // TODO add your handling code here:
        
        EnvironmentSensorManagementType type = (EnvironmentSensorManagementType) combo_Organization.getSelectedItem();

        directory.createEnvironmentSensorManagement(type);
        //directory.createEnvironmentManagement(type);
        populateTable();
    }//GEN-LAST:event_btn_add_orgActionPerformed

    private void btn_delete_OrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_OrgActionPerformed
        // TODO add your handling code here:
           // TODO add your handling code here:
        int selectedRow = tbl_org.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select the row");
            return;
        }
        Organization org = (Organization) tbl_org.getValueAt(selectedRow, 0);
        directory.DeleteOrganization(org);
        populateTable();
        JOptionPane.showMessageDialog(null, "Organization deleted Succesfully");
    }//GEN-LAST:event_btn_delete_OrgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_org;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete_Org;
    private javax.swing.JComboBox combo_Organization;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_org;
    // End of variables declaration//GEN-END:variables
}
