/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EnvironmentSensorEnterprise.SensorManagement;

import userinterface.EnvironmentSensorEnterprise.AirPollution.NotifytoAirPolltuionSolutionDepartment;
import userinterface.EnvironmentSensorEnterprise.AirPollution.ViewAirPollutionWorkQueue;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Oragnization.EnvironmentSensorOrganization;
import Business.UserAccount.UserAccount;
import userinterface.EnvironmentSensorEnterprise.AirPollution.AirPollutionSensorJPanel;
import userinterface.EnvironmentSensorEnterprise.FloodManagement.FloodManagementSensorJPanel;
import userinterface.EnvironmentSensorEnterprise.WasteManagement.WasteManagementSensor;
import userinterface.EnvironmentSensorEnterprise.NoisePollutionManagement.NoisePollutionManagementSensorJPanel;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
/**
 *
 * @author aishw
 */
public class SensorManagementWorkArea extends javax.swing.JPanel {
    
    private JPanel userProcessContainer; 
    private UserAccount account; 
    private EnvironmentSensorOrganization organization; 
    private Enterprise enterprise; 
    private EcoSystem business;
    /**
     * Creates new form SensorManagementWorkArea
     */
    public SensorManagementWorkArea(JPanel userProcessContainer, UserAccount account, EnvironmentSensorOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        
        lblEnterprisevalue.setText(enterprise.getName());
        lblOrganizationvalue.setText(account.getEmp().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        lblOrganizationvalue = new javax.swing.JLabel();
        lblEnterprise2 = new javax.swing.JLabel();
        lblEnterprisevalue = new javax.swing.JLabel();
        btnWasteManagement = new javax.swing.JButton();
        btnAirPollutionManagement1 = new javax.swing.JButton();
        btnNoiePollutionManagement = new javax.swing.JButton();
        btnFloodManagement = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 102));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sensor Management Work Area");
        add(jLabel1);
        jLabel1.setBounds(279, 10, 399, 31);

        lblEnterprise.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEnterprise.setText("Enterprise");
        add(lblEnterprise);
        lblEnterprise.setBounds(233, 80, 110, 47);

        lblOrganizationvalue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOrganizationvalue.setText("<value>");
        add(lblOrganizationvalue);
        lblOrganizationvalue.setBounds(370, 140, 308, 30);

        lblEnterprise2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEnterprise2.setText("Organization");
        add(lblEnterprise2);
        lblEnterprise2.setBounds(190, 140, 140, 30);

        lblEnterprisevalue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEnterprisevalue.setText("<value>");
        add(lblEnterprisevalue);
        lblEnterprisevalue.setBounds(370, 86, 308, 34);

        btnWasteManagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnWasteManagement.setText("Waste Management");
        btnWasteManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWasteManagementActionPerformed(evt);
            }
        });
        add(btnWasteManagement);
        btnWasteManagement.setBounds(347, 399, 340, 42);

        btnAirPollutionManagement1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAirPollutionManagement1.setText("Air Pollution Management");
        btnAirPollutionManagement1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirPollutionManagement1ActionPerformed(evt);
            }
        });
        add(btnAirPollutionManagement1);
        btnAirPollutionManagement1.setBounds(348, 219, 340, 42);

        btnNoiePollutionManagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNoiePollutionManagement.setText("Noise Pollution Management");
        btnNoiePollutionManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoiePollutionManagementActionPerformed(evt);
            }
        });
        add(btnNoiePollutionManagement);
        btnNoiePollutionManagement.setBounds(347, 279, 340, 42);

        btnFloodManagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFloodManagement.setText("Flood Management");
        btnFloodManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFloodManagementActionPerformed(evt);
            }
        });
        add(btnFloodManagement);
        btnFloodManagement.setBounds(347, 339, 340, 42);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sensor.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 50, 870, 490);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAirPollutionManagement1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirPollutionManagement1ActionPerformed
        // TODO add your handling code here:
        AirPollutionSensorJPanel airPollutionSensorManagement = new AirPollutionSensorJPanel(userProcessContainer, account, organization, enterprise, business);
        userProcessContainer.add("airPollutionSensorJPanel", airPollutionSensorManagement);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAirPollutionManagement1ActionPerformed

    private void btnNoiePollutionManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoiePollutionManagementActionPerformed
        // TODO add your handling code here:
        NoisePollutionManagementSensorJPanel noisePollutionSensorManagement = new NoisePollutionManagementSensorJPanel(userProcessContainer, account, organization, enterprise, business);
        userProcessContainer.add("noisePollutionSensorManagement", noisePollutionSensorManagement);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNoiePollutionManagementActionPerformed

    private void btnFloodManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFloodManagementActionPerformed
        // TODO add your handling code here:
        FloodManagementSensorJPanel floodsensor = new FloodManagementSensorJPanel(userProcessContainer, account, organization, enterprise, business);
        userProcessContainer.add("floodsensor", floodsensor);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnFloodManagementActionPerformed

    private void btnWasteManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWasteManagementActionPerformed
        // TODO add your handling code here:
        WasteManagementSensor wasteSensorManagement = new WasteManagementSensor(userProcessContainer, account, organization, enterprise, business);
        userProcessContainer.add("garbageSensorManagementJPanel", wasteSensorManagement);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnWasteManagementActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAirPollutionManagement1;
    private javax.swing.JButton btnFloodManagement;
    private javax.swing.JButton btnNoiePollutionManagement;
    private javax.swing.JButton btnWasteManagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblEnterprise2;
    private javax.swing.JLabel lblEnterprisevalue;
    private javax.swing.JLabel lblOrganizationvalue;
    // End of variables declaration//GEN-END:variables
}
