/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SysAdminWorkarea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Network.Network;
import Business.Role.EnvironmentManagementAdminRole;
import Business.Role.EnvironmentSensorAdminRole;
import Business.Role.GovernmentAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apurv
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateTable();
        populateCityComboBox();
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_Admin.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[3];
                    row[0] = enterprise.getName();
                    row[1] = network.getName();
                    row[2] = userAccount.getUsname();

                    model.addRow(row);
                }
            }
        }
    }
    
    private void populateCityComboBox() {
        combo_city.removeAllItems();

        for (Network network : system.getNetworkList()) {
            combo_city.addItem(network);
        }
    }

    private void populateEnterpriseComboBox(Network network) {
        Combo_enterprise.removeAllItems();

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            Combo_enterprise.addItem(enterprise);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        combo_city = new javax.swing.JComboBox();
        Combo_enterprise = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_usrname = new javax.swing.JTextField();
        txt_passwrd = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Admin = new javax.swing.JTable();
        btn_back = new javax.swing.JButton();
        txt_submit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 102));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("City");
        add(jLabel1);
        jLabel1.setBounds(30, 420, 130, 22);

        combo_city.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_city.setForeground(new java.awt.Color(0, 0, 51));
        combo_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_cityActionPerformed(evt);
            }
        });
        add(combo_city);
        combo_city.setBounds(276, 418, 227, 25);

        Combo_enterprise.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Combo_enterprise.setForeground(new java.awt.Color(0, 0, 51));
        Combo_enterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_enterpriseActionPerformed(evt);
            }
        });
        add(Combo_enterprise);
        Combo_enterprise.setBounds(276, 474, 227, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Enterprise");
        add(jLabel3);
        jLabel3.setBounds(26, 474, 150, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Username");
        add(jLabel2);
        jLabel2.setBounds(26, 590, 140, 22);

        txt_usrname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_usrname.setForeground(new java.awt.Color(0, 0, 51));
        add(txt_usrname);
        txt_usrname.setBounds(276, 591, 227, 23);

        txt_passwrd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_passwrd.setForeground(new java.awt.Color(0, 0, 51));
        txt_passwrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwrdActionPerformed(evt);
            }
        });
        add(txt_passwrd);
        txt_passwrd.setBounds(276, 645, 227, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Password");
        add(jLabel4);
        jLabel4.setBounds(26, 644, 130, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Name");
        add(jLabel5);
        jLabel5.setBounds(26, 537, 130, 22);

        txt_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_name.setForeground(new java.awt.Color(0, 0, 51));
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        add(txt_name);
        txt_name.setBounds(276, 538, 227, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Manage Enterprise Admin");
        add(jLabel6);
        jLabel6.setBounds(209, 22, 340, 29);

        tbl_Admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterperise", "Network", "UserName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_Admin);

        add(jScrollPane2);
        jScrollPane2.setBounds(137, 131, 452, 100);

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        btn_back.setText("<<Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        add(btn_back);
        btn_back.setBounds(20, 10, 95, 50);

        txt_submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/submit.png"))); // NOI18N
        txt_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_submitActionPerformed(evt);
            }
        });
        add(txt_submit);
        txt_submit.setBounds(276, 710, 290, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sysadmin.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(0, -80, 970, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void combo_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_cityActionPerformed

        Network network = (Network) combo_city.getSelectedItem();
        if (network != null) {
            populateEnterpriseComboBox(network);
        }

    }//GEN-LAST:event_combo_cityActionPerformed

    private void Combo_enterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_enterpriseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_enterpriseActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_passwrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwrdActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
     userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        //sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btn_backActionPerformed

    private void txt_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_submitActionPerformed
        // TODO add your handling code here:
        String name = txt_name.getText();
        String pss = txt_passwrd.getText();
        String user =txt_usrname.getText();
        
        if(name.isEmpty() || pss.isEmpty() || user.isEmpty()){
         JOptionPane.showMessageDialog(null, "No field should be blank");
        }
        else{
        try {
            Enterprise enterprise = (Enterprise) Combo_enterprise.getSelectedItem();

            String username = txt_usrname.getText();
            String password = String.valueOf(txt_passwrd.getPassword());
            

            Employee employee = enterprise.getEmployeeDirectory().createEmployee(name);
            if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.EnvManagement) {
                if (system.UniqueUserName(username)) {
                    UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new EnvironmentManagementAdminRole());
                } else {
                    JOptionPane.showMessageDialog(null, "User name already exist");
                }
            } else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.Government) {
                if (system.UniqueUserName(username)) {
                    UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new GovernmentAdminRole());
                } else {
                    JOptionPane.showMessageDialog(null, "User name already exist");
                }
            } else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.SensorManagement) {
                if (system.UniqueUserName(username)) {
                    UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new EnvironmentSensorAdminRole());
                } else {
                    JOptionPane.showMessageDialog(null, "User name already exist");
                }
            }
            populateTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something is wrong! You dont have an enterprise it seems");
        }
        }
    }//GEN-LAST:event_txt_submitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Combo_enterprise;
    private javax.swing.JButton btn_back;
    private javax.swing.JComboBox combo_city;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_Admin;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_passwrd;
    private javax.swing.JButton txt_submit;
    private javax.swing.JTextField txt_usrname;
    // End of variables declaration//GEN-END:variables
}
