/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GovWorkArea;


import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Oragnization.Organization.GovernmentType;
import Business.Oragnization.Organization;
import Business.Oragnization.OrganizationDirectory;

/**
 *
 * @author apurv
 */
public class GovernmentOrganizationJPanel extends javax.swing.JPanel {

    private OrganizationDirectory directory;
    private JPanel userProcessContainer;
    /**
     * Creates new form GovernmentEnterpriseJPanel
     */
    public GovernmentOrganizationJPanel(JPanel userProcessContainer, OrganizationDirectory directory) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.directory = directory;
        
        populateTable();
        populateCombo();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_govorg.getModel();

        model.setRowCount(0);

        for (Organization organization : directory.getOrganizationList()) {
            Object[] row = new Object[1];

            row[0] = organization;

            model.addRow(row);
        }
    }
    
    private void populateCombo() {
        combo_org.removeAllItems();
        for (Organization.GovernmentType type : Organization.GovernmentType.values()) {
            if (!type.getValue().equals(Organization.GovernmentType.GovernmentAdmin.getValue())) {
                combo_org.addItem(type);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        combo_org = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_govorg = new javax.swing.JTable();
        btn_Add_org = new javax.swing.JButton();
        btn_delete_org = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 102));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Organization Type ");
        add(jLabel1);
        jLabel1.setBounds(60, 250, 230, 22);

        combo_org.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_org.setForeground(new java.awt.Color(0, 0, 51));
        combo_org.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_org.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_orgActionPerformed(evt);
            }
        });
        add(combo_org);
        combo_org.setBounds(300, 250, 268, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Government Organization");
        add(jLabel2);
        jLabel2.setBounds(240, 40, 380, 29);

        tbl_govorg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_govorg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_govorg);

        add(jScrollPane2);
        jScrollPane2.setBounds(107, 111, 570, 120);

        btn_Add_org.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Add_org.setText("Add organization");
        btn_Add_org.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add_orgActionPerformed(evt);
            }
        });
        add(btn_Add_org);
        btn_Add_org.setBounds(140, 420, 157, 21);

        btn_delete_org.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_delete_org.setText("Delete Organization");
        btn_delete_org.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_orgActionPerformed(evt);
            }
        });
        add(btn_delete_org);
        btn_delete_org.setBounds(360, 420, 177, 25);

        btn_Back.setText("<<BACK");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });
        add(btn_Back);
        btn_Back.setBounds(60, 20, 95, 21);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/govorganization.jpg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 1030, 710);
    }// </editor-fold>//GEN-END:initComponents

    private void combo_orgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_orgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_orgActionPerformed

    private void btn_Add_orgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add_orgActionPerformed
        // TODO add your handling code here:
         GovernmentType type = (GovernmentType) combo_org.getSelectedItem();

        directory.createGovernmentOfficial(type);
        //directory.createEnvironmentManagement(type);
        populateTable();
    }//GEN-LAST:event_btn_Add_orgActionPerformed

    private void btn_delete_orgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_orgActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int selectedRow = tbl_govorg.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select the row");
            return;
        }
        Organization org = (Organization) tbl_govorg.getValueAt(selectedRow, 0);
        directory.DeleteOrganization(org);
        populateTable();
        JOptionPane.showMessageDialog(null, "Organization deleted Succesfully");
    }//GEN-LAST:event_btn_delete_orgActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btn_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add_org;
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_delete_org;
    private javax.swing.JComboBox combo_org;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_govorg;
    // End of variables declaration//GEN-END:variables
}
