/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ResidentOrganization;

import Business.Oragnization.OrganizationDirectory;
import Business.Oragnization.ResidentOrganization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apurv
 */
public class NotifyResidentJPanel extends javax.swing.JPanel {
    private OrganizationDirectory directory;
    private UserAccount userAccount;
    private JPanel userProcessContainer;

    public CitizenNotificationJPanel(JPanel userProcessContainer, UserAccount userAccount, OrganizationDirectory directory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.directory = directory;
        
        populateTable();
    }
    /**
     * Creates new form NotifyResidentJPanel
     */
    public NotifyResidentJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_wrk_request = new javax.swing.JTable();
        btn_BACK = new javax.swing.JButton();
        btn_view_Full_Message = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("RESIDENT WORK QUEUE");

        tbl_wrk_request.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbl_wrk_request.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Work_Request_ID", "Sender", "Message"
            }
        ));
        jScrollPane1.setViewportView(tbl_wrk_request);

        btn_BACK.setText("<<BACK");
        btn_BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BACKActionPerformed(evt);
            }
        });

        btn_view_Full_Message.setText("View_Full_Message");
        btn_view_Full_Message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view_Full_MessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_view_Full_Message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_BACK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(btn_BACK)
                .addGap(31, 31, 31)
                .addComponent(btn_view_Full_Message)
                .addContainerGap(186, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BACKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BACKActionPerformed

    private void btn_view_Full_MessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view_Full_MessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view_Full_MessageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BACK;
    private javax.swing.JButton btn_view_Full_Message;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_wrk_request;
    // End of variables declaration//GEN-END:variables

    public void populateTable() {
        ResidentWorkRequest cit_wrs = null;
        DefaultTableModel model = (DefaultTableModel) tbl_wrk_request.getModel();
        model.setRowCount(0);
        
        for(Organization organization : directory.getOrganizationList())
        {
            if(organization instanceof ResidentOrganization) {
        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof CitizenWorkRequest) 
            {
                cit_wrs = (CitizenWorkRequest)wr;
            
                if(cit_wrs.getAirPollutionSensor()!=null)
                {
                Object[] row1 = new Object[3];
                row1[0] = cit_wrs;
                row1[1] = cit_wrs.getSender();
                row1[2] = cit_wrs.getAirPollutionMessage();
                model.addRow(row1);
                }
                            
                else if(cit_wrs.getFloodAlertSensorList() != null)
                {
                Object[] row = new Object[3];
                row[0] = cit_wrs;
                row[1] = cit_wrs.getSender();
                row[2] = cit_wrs.getFloodAlertMessage();
                model.addRow(row);
                }
                
            }
        }
      }
        }    }
}
