/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ResidentOrganization;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Oragnization.ResidentOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author apurv
 */
public class ResidentWorkAreaJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final UserAccount account;
    private final ResidentOrganization organization;
    private final Enterprise enterprise;
    private final EcoSystem business;

    /**
     * Creates new form ResidentWorkAreaJPanel
     */
    
    public ResidentWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, ResidentOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Btn_View_Notification = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 102));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resident Work Area");
        add(jLabel1);
        jLabel1.setBounds(0, 23, 970, 44);

        Btn_View_Notification.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_View_Notification.setText("View Notification");
        Btn_View_Notification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_View_NotificationActionPerformed(evt);
            }
        });
        add(Btn_View_Notification);
        Btn_View_Notification.setBounds(350, 180, 210, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/resident.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(-90, -160, 1150, 710);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_View_NotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_View_NotificationActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        NotifyResidentJPanel citizenNotificationJPanel = new NotifyResidentJPanel(userProcessContainer, account, enterprise.getOrganizationDirectory());
        userProcessContainer.add("citizenNotificationJPanel", citizenNotificationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_Btn_View_NotificationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_View_Notification;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
