/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EnvironmentSensorEnterprise.NoisePollutionManagement;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Oragnization.EnvironmentSensorOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author aishw
 */
public class NoisePollutionManagementSensorJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer; 
    private UserAccount account; 
    private EnvironmentSensorOrganization organization; 
    private Enterprise enterprise; 
    private EcoSystem business;
    /**
     * Creates new form NoisePollutionSensorManagementJPanel
     */
    public NoisePollutionManagementSensorJPanel(JPanel userProcessContainer, UserAccount account, EnvironmentSensorOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSendRequest = new javax.swing.JButton();
        btnViewrequests = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 102));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Noise Pollution Sensor Management");
        add(jLabel1);
        jLabel1.setBounds(20, 20, 470, 60);

        btnSendRequest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSendRequest.setText("Send Request");
        btnSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestActionPerformed(evt);
            }
        });
        add(btnSendRequest);
        btnSendRequest.setBounds(127, 127, 155, 22);

        btnViewrequests.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnViewrequests.setText("View Sent Requsts");
        btnViewrequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewrequestsActionPerformed(evt);
            }
        });
        add(btnViewrequests);
        btnViewrequests.setBounds(348, 127, 196, 22);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back_Final.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(180, 210, 70, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/control-noise.jpg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 950, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestActionPerformed
        // TODO add your handling code here:
        NotifyToNoisePollutionSolutionDepartmentJPanel NotifyToNoisePollutionSolutionDepartment;
        try {
            NotifyToNoisePollutionSolutionDepartment = new NotifyToNoisePollutionSolutionDepartmentJPanel(userProcessContainer, account, business, enterprise.getOrganizationDirectory());
            userProcessContainer.add("NotifyToNoisePollutionSolutionDepartmentJPanel", NotifyToNoisePollutionSolutionDepartment);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } catch (IOException ex) {
            Logger.getLogger(NoisePollutionManagementSensorJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSendRequestActionPerformed

    private void btnViewrequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewrequestsActionPerformed
        // TODO add your handling code here:
        ViewNoisePollutionWorkQueueJPanel viewWorkQueueJPanel = new ViewNoisePollutionWorkQueueJPanel(userProcessContainer, account, enterprise.getOrganizationDirectory());
        userProcessContainer.add("viewWorkQueueJPanel", viewWorkQueueJPanel);
        CardLayout layot = (CardLayout) userProcessContainer.getLayout();
        layot.next(userProcessContainer);
    }//GEN-LAST:event_btnViewrequestsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component compnt = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendRequest;
    private javax.swing.JButton btnViewrequests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
